name: CD

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "Checkout Master Branch"
        uses: actions/checkout@v2
        
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1.0.0
        
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1
        
      - name: Nuget Restore
        run: |
          nuget restore HoneybeeSchema.sln
          nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory packages

      - name: MSBuild
        run: |
          msbuild /p:Configuration=Release HoneybeeSchema.sln
          
      - name: Run Unit Tests
        run: |
          ./packages/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe src/HoneybeeSchema.Test/bin/Release/HoneybeeSchema.Test.dll

      - name: Deploy
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          BUILD_VERSION: $(monodis --assembly src/HoneybeeSchema/bin/Release/HoneybeeSchema.dll | grep -Po '([0-9]{1,}\.)+[0-9]{1,}')
        run: |
          nuget pack src/HoneybeeSchema/HoneybeeSchema.csproj -Properties Configuration=Release -Version $BUILD_VERSION -Verbosity detailed
          nuget push HoneybeeSchema.$BUILD_VERSION.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
